version: '3'

services:
  nginx:
    image: nginx:1.13-alpine
    ports:
      - ${VIRTUAL_PORT}:80
    restart: always
    env_file: .env
    volumes:
      - ./docker/settings/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./client:/var/www/client
    networks:
      - front
      - back

  node:
    image: node:8.9.3-alpine
    ports:
      - 3000
    restart: always
    env_file: .env
    volumes:
      - ./client:/var/www/client
    working_dir: /var/www/client
    environment:
      - PORT=3000
      - WP_URL=http://wordpress:80
    command: 'npm start'
    networks:
      - back

  wordpress:
    build: ./docker/dockerfile/wordpress
    ports:
      - 9000
    restart: always
    env_file: .env
    volumes:
      - ./docker/settings/wordpress:/usr/local/etc/php:ro
      - data-api:/var/www/html:rw
    depends_on:
      - mysql
    networks:
      - back

  mysql:
    image: mysql:5.7
    ports:
      - 3306
    restart: always
    env_file: .env
    volumes:
      - data-db:/var/lib/mysql:rw
    networks:
      - back

volumes:
  data-api:
  data-db:

networks:
  front:
    external: true
  back:
