version: '3'

services:
  nginx:
    image: nginx:1.13-alpine
    ports:
      - ${VIRTUAL_PORT}:80
    restart: always
    env_file: .env
    volumes:
      - data-wp:/var/www/html:ro
      - ./docker/settings/nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - wordpress
      - node
      - mysql
    networks:
      - front
      - back

  node:
    image: node:8.9.3-alpine
    ports:
      - 3000
    restart: always
    env_file: .env
    volumes:
      - ./client:/usr/src/app
    depends_on:
      - wordpress
      - mysql
    working_dir: /usr/src/app
    command: 'npm start'
    networks:
      - back

  wordpress:
    build: ./docker/dockerfile/wordpress
    ports:
      - 9000
    restart: always
    env_file: .env
    volumes:
      - data-wp:/var/www/html:rw
      - ./docker/settings/wordpress:/usr/local/etc/php:ro
    depends_on:
      - mysql
    networks:
      - back

  mysql:
    image: mysql:5.7
    ports:
      - 3306
    restart: always
    env_file: .env
    volumes:
      - data-db:/var/lib/mysql:rw
    networks:
      - back

volumes:
  data-wp:
  data-db:

networks:
  front:
    external: true
  back:
