version: '3'

services:
  nginx:
    image: nginx:mainline-alpine
    ports:
      - ${VIRTUAL_PORT}:80
    restart: always
    env_file: .env
    volumes:
      - ./setting/nginx/conf.d:/etc/nginx/conf.d:ro
    networks:
      - front
      - back

  wordpress:
    build: ./docker/wordpress
    ports:
      - 9000
    restart: always
    networks:
      - back

networks:
  front:
    external: true
  back:
